modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Creators-of-Create/Create/issues"
license="MIT"

[[mods]]
modId="createponder"
# The Implementation-Version property in the jar's MANIFEST.MF file will be used as the mod version at runtime 
version="${file.jarVersion}"
displayName="Create Ponder"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/create"
logoFile="logo.png"
#credits=""
authors="simibubi, almostreliable, westernat"
description='''
Technology that empowers the player.'''

[[dependencies.createponder]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createponder]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createponder]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.10,0.6.11)"
    ordering="AFTER"
    side="CLIENT"
